In [1]:
import pandas as pd
import time
import numpy as np

# Filling of missing values

In [2]:
Training = pd.read_csv('Data/training_input.csv', delimiter=',')

In [30]:
Training.shape

(613220, 57)

In [3]:
TrainingMissing = Training.iloc[pd.isnull(Training).any(1).nonzero()[0]]

In [4]:
TrainingMissing = TrainingMissing.reset_index(drop=True)

In [5]:
TrainingMissing.head()

ID 
 date 
 product_id 
 09:30:00 
 09:35:00 
 09:40:00 
 09:45:00 
 09:50:00 
 09:55:00 
 10:00:00 
 ... 
 13:10:00 
 13:15:00 
 13:20:00 
 13:25:00 
 13:30:00 
 13:35:00 
 13:40:00 
 13:45:00 
 13:50:00 
 13:55:00 
 
 
 
 
 0 
 6 
 1 
 267 
 8091607.23 
 200855.00 
 254585.18 
 182094.78 
 239248.65 
 295739.52 
 224983.14 
 ... 
 48647.50 
 134951.50 
 172651.50 
 231768.23 
 NaN 
 10164.00 
 161273.64 
 245219.00 
 118459.64 
 70953.90 
 
 
 1 
 23 
 1 
 409 
 3967038.72 
 49270.40 
 72597.00 
 49056.54 
 105244.80 
 109664.24 
 72702.00 
 ... 
 97035.72 
 94930.00 
 109808.12 
 53813.32 
 32897.56 
 142312.95 
 20532.20 
 20807.80 
 38365.11 
 NaN 
 
 
 2 
 29 
 1 
 447 
 NaN 
 4902746.25 
 123692.64 
 126432.00 
 90729.22 
 225985.34 
 127063.09 
 ... 
 110715.28 
 45155.70 
 116440.34 
 106385.16 
 89622.00 
 124051.29 
 68860.00 
 79177.41 
 299000.72 
 185450.66 
 
 
 3 
 30 
 1 
 449 
 5642713.00 
 168978.59 
 252366.66 
 212968.04 
 92013.80 
 102185.00 
 186739.00 
 ... 
 121237.65 
 70216.02 
 215304.70 
 57243.78 
 67538.61 
 301868.55 
 45289.71 
 200126.97 
 99121.12 
 79086.00 
 
 
 4 
 60 
 1 
 839 
 NaN 
 7261088.04 
 118917.12 
 178083.00 
 99840.15 
 66552.40 
 115056.54 
 ... 
 85395.84 
 37900.00 
 79485.00 
 135654.40 
 56820.66 
 53071.20 
 75540.00 
 31273.56 
 50951.73 
 68079.56 
 
 
 
 5 rows × 57 columns

In [17]:
#TrainingMissing.iloc[0,3:]

# First Idea

Our first idea is to use the complete days for the same product. Thus we want to see if there is a correlation between the time series of a same product.

In [6]:
Test267 = Training[Training['product_id'] == 267].reset_index(drop=True)

In [7]:
Test267.head()

ID 
 date 
 product_id 
 09:30:00 
 09:35:00 
 09:40:00 
 09:45:00 
 09:50:00 
 09:55:00 
 10:00:00 
 ... 
 13:10:00 
 13:15:00 
 13:20:00 
 13:25:00 
 13:30:00 
 13:35:00 
 13:40:00 
 13:45:00 
 13:50:00 
 13:55:00 
 
 
 
 
 0 
 6 
 1 
 267 
 8091607.2300 
 200855.000 
 254585.1800 
 182094.7800 
 239248.6500 
 295739.5200 
 224983.1400 
 ... 
 48647.5000 
 134951.5000 
 172651.5000 
 231768.23 
 NaN 
 10164.00 
 161273.64 
 245219.00 
 118459.64 
 70953.90 
 
 
 1 
 358 
 2 
 267 
 1510629.9114 
 496502.000 
 304086.0000 
 250097.9854 
 399503.9768 
 284460.0000 
 318015.0185 
 ... 
 211805.9877 
 328710.9809 
 351083.9796 
 370445.00 
 412514.00 
 198490.00 
 403884.00 
 205394.00 
 331584.00 
 400432.00 
 
 
 2 
 978 
 4 
 267 
 512487.7000 
 831157.760 
 1056646.0300 
 470614.6400 
 373647.6000 
 966734.0400 
 520505.3500 
 ... 
 1053542.4000 
 345372.1700 
 185485.3000 
 735669.22 
 678953.99 
 773766.99 
 532827.00 
 210624.81 
 728071.68 
 1022121.24 
 
 
 3 
 1598 
 6 
 267 
 131850.0000 
 718730.041 
 440755.9749 
 89555.9949 
 156017.0089 
 50605.0029 
 139679.9920 
 ... 
 71791.0000 
 17510.0000 
 73542.0000 
 52500.00 
 98056.00 
 31500.00 
 26265.00 
 150672.00 
 71832.00 
 103368.00 
 
 
 4 
 1950 
 7 
 267 
 334122.0000 
 41586.000 
 80248.0000 
 93080.0000 
 119105.0000 
 63184.0000 
 125019.0000 
 ... 
 89032.0000 
 76002.0000 
 57360.0000 
 97512.00 
 57360.00 
 50190.00 
 63140.00 
 47388.00 
 27284.00 
 113444.00 
 
 
 
 5 rows × 57 columns

In [8]:
Test267 = Test267.drop(pd.isnull(Test267).any(1).nonzero()[0]).reset_index(drop = True)

In [9]:
del Test267['ID'],Test267['date'],Test267['product_id']

In [10]:
print np.corrcoef(np.array(Test267.iloc[range(0,6)]))

[[ 1.         -0.0203954   0.08745534  0.49530647  0.0572036   0.07145631]
 [-0.0203954   1.          0.01902363 -0.19910509  0.02233614 -0.16763977]
 [ 0.08745534  0.01902363  1.          0.03151256 -0.15913989  0.32836028]
 [ 0.49530647 -0.19910509  0.03151256  1.          0.01627805  0.24421717]
 [ 0.0572036   0.02233614 -0.15913989  0.01627805  1.         -0.19684703]
 [ 0.07145631 -0.16763977  0.32836028  0.24421717 -0.19684703  1.        ]]


The correlations are low we drop this idea.

## Second idea

Check for correlations betwenn product on the same date

In [16]:
print "nombres de dates",Training['date'].value_counts().shape
print "nombres de produits",Training['product_id'].value_counts().shape

nombres de dates (1882,)
nombres de produits (352,)


In [17]:
TestFull = Training.drop(pd.isnull(Training).any(1).nonzero()[0]).reset_index(drop = True)

In [18]:
TestFull['date'].value_counts()

1516    351
777     350
876     349
331     349
1673    349
1405    349
890     349
1555    349
478     348
72      348
967     348
963     348
1756    348
1729    348
882     348
1685    348
1200    348
1184    348
296     348
1706    348
306     347
1193    347
1376    347
1297    347
1531    347
1270    347
449     347
746     346
1866    346
848     346
       ... 
904      95
616      95
207      95
1609     94
915      93
996      93
1005     92
144      90
1377     90
1732     89
1472     88
47       88
457      88
48       88
712      87
63       87
431      85
687      85
538      85
617      83
1412     80
1056     78
1735     30
314       2
103       1
1110      1
311       1
1495      1
693       1
1208      1
Name: date, dtype: int64

In [19]:
TestDate = TestFull[TestFull['date']==1516]

In [20]:
del TestDate['ID'],TestDate['date'],TestDate['product_id']

In [21]:
TestDate.head()

09:30:00 
 09:35:00 
 09:40:00 
 09:45:00 
 09:50:00 
 09:55:00 
 10:00:00 
 10:05:00 
 10:10:00 
 10:15:00 
 ... 
 13:10:00 
 13:15:00 
 13:20:00 
 13:25:00 
 13:30:00 
 13:35:00 
 13:40:00 
 13:45:00 
 13:50:00 
 13:55:00 
 
 
 
 
 410922 
 4037832.78 
 1347850.40 
 2070120.15 
 4895197.20 
 2778297.48 
 1454243.73 
 1200015.85 
 1887696.250 
 1553792.49 
 2314705.17 
 ... 
 726977.66 
 1008437.08 
 1635168.97 
 1141354.1952 
 2580499.68 
 801452.80 
 2260203.910 
 912579.9800 
 3465323.3800 
 1490994.94 
 
 
 410923 
 364176.00 
 265503.70 
 717347.80 
 633052.88 
 469596.42 
 393848.00 
 373838.00 
 387502.500 
 245742.12 
 324921.84 
 ... 
 341464.40 
 356353.20 
 501259.20 
 402682.3200 
 569794.82 
 261605.52 
 379157.600 
 937992.7600 
 401333.5800 
 507725.00 
 
 
 410924 
 864817.13 
 2376450.00 
 1976189.23 
 2265644.25 
 781484.40 
 1215011.52 
 3943854.72 
 1734996.900 
 1984813.20 
 1689480.00 
 ... 
 337288.00 
 337212.00 
 319824.00 
 293172.0000 
 1158764.03 
 884114.96 
 837339.174 
 1017310.1400 
 482673.4500 
 629578.98 
 
 
 410925 
 1520075.04 
 834019.35 
 1347795.12 
 1232024.33 
 563066.24 
 1066079.52 
 1715451.21 
 1554975.400 
 1056590.00 
 799837.08 
 ... 
 304641.81 
 369595.71 
 344968.00 
 270383.0400 
 606272.42 
 179452.56 
 189076.510 
 222239.0000 
 287481.7400 
 211167.00 
 
 
 410926 
 2426504.85 
 2209152.05 
 4198626.00 
 3765510.70 
 1585601.88 
 1207388.64 
 2129337.76 
 857580.376 
 1049437.43 
 1097689.47 
 ... 
 1146243.60 
 3160333.77 
 1697558.20 
 1248108.9300 
 2246511.09 
 716934.20 
 1879435.080 
 2244303.7596 
 1645054.6685 
 1194025.28 
 
 
 
 5 rows × 54 columns

In [22]:
Corr = np.corrcoef(np.array(TestDate))
Corr.shape

(351, 351)

In [23]:
for i in range(0, Corr.shape[0]) : 
    for j in range(0, Corr.shape[0]) : 
        
        if i<=j :
            Corr[i][j] = 0

In [24]:
print np.max(Corr)
print np.min(Corr)

0.935925146551
-0.339074715917


In [27]:
for i in range(0,Corr.shape[0]) : 
    for j in range(0,Corr.shape[0]) : 
        
        if Corr[i][j] == np.max(Corr) :
            print i,j

301 61


In [26]:
TestDate = TestFull[TestFull['date']==1516]
print TestDate['product_id'].iloc[301]
print TestDate['product_id'].iloc[61]

4956
868


In [22]:
TestDate = TestDate[(TestDate['product_id']==4956) | (TestDate['product_id']==868)]

In [23]:
TestDate.shape

(2, 57)

In [24]:
del TestDate['ID'],TestDate['date'],TestDate['product_id']

In [25]:
Corr = np.corrcoef(np.array(TestDate))

In [26]:
Corr

array([[ 1.        ,  0.93592515],
       [ 0.93592515,  1.        ]])

In [27]:
TestCorr = Training[(Training['product_id']==4956) | (Training['product_id']==868)]

In [57]:
Result=[]

for day in range(1,1885) : 
    
    Temp = TestFull[(TestFull['date']==day)]
    Temp = Temp[(Temp['product_id']==4956) | (Temp['product_id']==868)]
    del Temp['ID'],Temp['date'],Temp['product_id']
    if Temp.shape[0] == 2 : 
        Result.append(np.corrcoef(np.array(Temp))[0][1])

In [58]:
sum(Result) / float(len(Result))

0.61847887958243453

In [36]:
print temp

None


TypeError: only integer arrays with one element can be converted to an index